### ISSUE TITLE
Warning messages for multiple attachments

### ISSUE THREAD

**Issue by GauravPatni** [taljacobson/flutter_mailer#13]
Thanks for creating this package.
Getting following warning messages when **attaching more than one file** (**Android 4.4.4**)

```
W/Bundle  ( 6843): Key android.intent.extra.TEXT expected ArrayList<CharSequence> but value was a java.lang.String.  The default value <null> was returned.
W/Bundle  ( 6843): Attempt to cast generated internal exception:
W/Bundle  ( 6843): java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
W/Bundle  ( 6843): 	at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1367)
W/Bundle  ( 6843): 	at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:4767)
W/Bundle  ( 6843): 	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:7287)
W/Bundle  ( 6843): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1417)
W/Bundle  ( 6843): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1089)
W/Bundle  ( 6843): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1071)
W/Bundle  ( 6843): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
W/Bundle  ( 6843): 	at com.dataxad.fluttermailer.FlutterMailerPlugin.mail(FlutterMailerPlugin.java:167)
W/Bundle  ( 6843): 	at com.dataxad.fluttermailer.FlutterMailerPlugin.onMethodCall(FlutterMailerPlugin.java:50)
W/Bundle  ( 6843): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
W/Bundle  ( 6843): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
W/Bundle  ( 6843): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
W/Bundle  ( 6843): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/Bundle  ( 6843): 	at android.os.MessageQueue.next(MessageQueue.java:138)
W/Bundle  ( 6843): 	at android.os.Looper.loop(Looper.java:123)
W/Bundle  ( 6843): 	at android.app.ActivityThread.main(ActivityThread.java:5052)
W/Bundle  ( 6843): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/Bundle  ( 6843): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/Bundle  ( 6843): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
W/Bundle  ( 6843): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
W/Bundle  ( 6843): 	at dalvik.system.NativeStart.main(Native Method)
I/Timeline( 6843): Timeline: Activity_launch_request time:2353015
I/flutter ( 6843): Send OK
I/Timeline( 6843): Timeline: Activity_idle id: android.os.BinderProxy@4207a750 time:2361455
Reloaded 1 of 457 libraries in 673ms.
I/flutter ( 6843): File created
```

refer example code 

```dart
import 'dart:async';
import 'dart:io';
import 'package:flutter/services.dart';
import 'package:flutter/material.dart';
import 'package:flutter_mailer/flutter_mailer.dart';
import 'package:path_provider/path_provider.dart';

void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  List<String> _emailAttachmentPath;
  test() async {
    final directory = await getTemporaryDirectory();
    final file = File('${directory.path}/test1.txt');
    file.writeAsStringSync('Test1', flush: true);

    final file1 = File('${directory.path}/test2.txt');
    file1.writeAsStringSync('Test1', flush: true);

    _emailAttachmentPath = [
      "${directory.path}/test2.txt",
      "${directory.path}/test1.txt"
    ];
    print("File created");
  }

  @override
  Widget build(BuildContext context) {
    test();
    return new MaterialApp(
      theme: ThemeData(primaryColor: Colors.red),
      home: new Scaffold(
        appBar: new AppBar(
          title: const Text('Plugin example app'),
        ),
        body: RaisedButton(
          child: Text("Send"),
          onPressed: () async {
            final MailOptions mailOptions = MailOptions(
              body: 'a long body for the email <br> with a subset of HTML',
              subject: 'the Email Subject',
              recipients: ['test@test.com'],
              isHTML: true,
              // bccRecipients: ['other@example.com'],
              // ccRecipients: ['third@example.com'],
              attachments: _emailAttachmentPath,
            );
            try {
              await FlutterMailer.send(mailOptions);
            } catch (e) {
              print("EMAIL - > $e");
            }

            print("Send OK");
          },
        ),
      ),
    );
  }
}



```

found following related forum links 

https://forums.xamarin.com/discussion/37040/problem-setting-email-text-with-multiple-attachments
https://stackoverflow.com/questions/15776416/java-lang-classcastexception-android-text-spannablestringbuilder-cannot-be-cast

Thanks,
Gaurav

**Comment by Mmisiek** [comment]
Why won't fix ? It is not fixable by workaround ?

**Comment by sourabhcodetrade** [comment]
I am facing the same issue any update on this?
