### ISSUE TITLE
RuntimeException Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by medyas** [taljacobson/flutter_mailer#47]
We are getting multiple crashes reports from crashlytics. it looks like the package tries to use the `result` object after it already emitted a result.
Could you add checks to avoid this issue

**Stacktrace**
```bash
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=564, result=0, data=null} to activity {com.bayt/com.baytjs.MainActivity}: java.lang.IllegalStateException: Reply already submitted
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5579)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5620)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:164)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
       at com.dataxad.flutter_mailer.MethodCallHandlerImpl.onActivityResult(MethodCallHandlerImpl.java:96)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:741)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:749)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:651)
       at android.app.Activity.dispatchActivityResult(Activity.java:8550)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5572)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5620)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by taljacobson** [comment]
can you provide some more information.
like devices affected, android version?
what version of the plugin is used?

**Comment by medyas** [comment]
Hello @taljacobson, thanks for your reply.
we are using `flutter_mailer: 2.0.0`
for the affected devices & android versions, please check the provided screenshots

![Screenshot 2021-12-19 at 16-04-56 JS App - Flutter – DartMessenger java line 164 – Firebase console](https://user-images.githubusercontent.com/13151636/146679888-2b4b0221-4311-477b-a4a2-dffd7a51c57c.png)
![Screenshot 2021-12-19 at 16-05-09 JS App - Flutter – DartMessenger java line 164 – Firebase console](https://user-images.githubusercontent.com/13151636/146679890-86a57cb8-a4fe-4ebf-a660-1d58407ec520.png)
